source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'sassc'
gem 'async'
gem 'sequel'
gem 'pg'

gem 'rack', '~> 3.1.13'
gem 'rackup', '~> 2.2.1'
gem 'falcon'

gem 'stack-service-base'

group :test do
  gem 'sqlite3'
  gem 'rspec'
  gem 'rack-test'
  gem 'rspec-benchmark'
  gem 'rspec_junit_formatter'
  gem 'async-rspec'
  gem "rspec-snapshot"
  gem 'testcontainers'

  gem 'simplecov'
  # gem 'simplecov-cobertura'
  gem 'yard'
end