require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: :rspec

desc "Run all tests"
task :test => :spec

desc "Run tests with coverage"
task :coverage do
  ENV['COVERAGE'] = 'true'
  Rake::Task[:spec].invoke
end
