services:
  webrtc-server-back:
    image: ${REGISTRY_HOST}/webrtc-server-komaroff-back/${CI_COMMIT_BRANCH}
    build:
      context: ../src_back
      dockerfile: ../docker/python/Dockerfile
      target: base
    ports:
      - "8000:8000"
    volumes:
      - vad_models:/app/models/vad
    depends_on:
      - audio_nats

  audio_nats:
    image: nats:2.11.6-scratch
    command: ["-js"]


  webrtc-server-whisper-python:
    image: ${REGISTRY_HOST}/webrtc-server-komaroff-whisper-python/${CI_COMMIT_BRANCH}
    build:
      context: ../src_whisper
      #      additional_contexts:
      #        docker: ../docker
      dockerfile: ../docker/python/Dockerfile
      target: whisper
    volumes:
      - asr_models_python:/app/models/asr
    depends_on:
      - audio_nats
    ports:
      - "9000:9000"

  webrtc-server-whisper-ruby:
    image: ${REGISTRY_HOST}/webrtc-server-komaroff-whisper-ruby/${CI_COMMIT_BRANCH}
    build:
      context: ../src_whisper_ruby
      dockerfile: ../docker/ruby/Dockerfile
      target: deploy
    volumes:
      - asr_models_ruby:/app/models/asr
    depends_on:
      - audio_nats
    ports:
      - "${WHISPER_RUBY_PORT:-7000}:7000"

  webrtc-server-whisper-cpp:
    image: ${REGISTRY_HOST}/webrtc-server-komaroff-whisper-cpp/${CI_COMMIT_BRANCH}
    build:
      context: ../src_whisper_c
      dockerfile: ../docker/cpp/Dockerfile
    volumes:
      - asr_models_cpp:/app/models/asr
    depends_on:
      - audio_nats
    environment:
      NATS_URL: nats://audio_nats:4222
      NATS_FRAMES_SUBJECT: nats.frames
      NATS_LOGS_SUBJECT: nats.logs

volumes:
  vad_models: {}
  asr_models_python: {}
  asr_models_ruby: {}
  asr_models_cpp: {}
