FROM ruby:3.3.0-alpine3.19  AS base
RUN apk add bash docker-cli-buildx git
RUN gem install build-labels:0.0.65 dry-stack:0.1.16

FROM base AS runner
WORKDIR /build
COPY . .

CMD ["bash", "-c", "-x", "\
    env && cd /build/docker && \
    export PATH=/usr/local/bundle/bin:$PATH && \
    VERSION_FILE=/build/.version && \
    if [ ! -s \"$VERSION_FILE\" ]; then \
      printf '%s\n' \"${CI_COMMIT_TAG:-0.0.0}\" > \"$VERSION_FILE\"; \
    fi && \
    REGISTRY_HOST=$CI_REGISTRY_HOST build-labels -n -c docker-compose.yml changed gitlab set_version to_dockerfiles to_compose > bake.yml && \
    export OTEL_RESOURCE_ATTRIBUTES=service.name=docker-builder,pipeline.id=${CI_PIPELINE_ID},project.name=${CI_PROJECT_NAME} && \
    cat bake.yml && \
    grep \"services: {}\" bake.yml || REGISTRY_HOST=$CI_REGISTRY_HOST docker buildx bake -f bake.yml $([ -z \"$CI_SKIP_PUSH\" ] && echo \"--push\") \
    "]
