services:
  webrtc-server-back:
    image: ${REGISTRY_HOST}/webrtc-server-back/${CI_COMMIT_BRANCH}
    build:
      context: ../src_back
#      additional_contexts:
#        docker: ../docker
      dockerfile: ../docker/python/Dockerfile
    ports:
      - "8000:8080"

#  webrtc-server-front:
#    image: ${REGISTRY_HOST}/webrtc-server-front/${CI_COMMIT_BRANCH}
#    build:
#      context: ../src_front
##      additional_contexts:
##        docker: ../docker
#      dockerfile: ../docker/ruby/Dockerfile
#    ports:
#      - "7000:7000"
