FROM ruby:3.3.0-alpine3.19 as base
RUN apk add git

RUN set -eux; \
    apt update; apt install -y --no-install-recommends ca-certificates curl; \
    install -m 0755 -d /etc/apt/keyrings; \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc; \
    chmod a+r /etc/apt/keyrings/docker.asc; \
    . /etc/os-release; \
    printf "Types: deb\nURIs: https://download.docker.com/linux/debian\nSuites: %s\nComponents: stable\nSigned-By: /etc/apt/keyrings/docker.asc\n" "$VERSION_CODENAME" \
      > /etc/apt/sources.list.d/docker.sources; \
    apt update; apt install -y --no-install-recommends docker-ce-cli docker-cli-buildx; \
    rm -rf /var/lib/apt/lists/*

RUN docker -v

RUN gem install build-labels:0.0.65 dry-stack:0.1.53

RUN apk add --no-cache openssh-client ca-certificates

WORKDIR /build
RUN mkdir -p /root/.ssh && mkdir -pv /root/.ssh/sockets
RUN echo -e 'Host *\n\tControlPersist yes\n\tControlMaster auto\n\tControlPath  /root/.ssh/sockets/%r@%h-%p\n\tBatchMode yes\n\tStrictHostKeyChecking no\n\tPort 22' > ~/.ssh/config
ADD . .

CMD ["sh", "-c", "\
    cat webrtc.drs  | dry-stack swarm_deploy --tls-domain=gis-master.ru -x ssh://gis-master.ru -- --prune \n\
"]
