FROM ruby:3.4.4-slim-bookworm AS base
RUN apt update && apt install -y --no-install-recommends openssh-client ca-certificates
RUN gem install build-labels:0.0.76 dry-stack:0.1.53
RUN install-docker-static 28

WORKDIR /build
RUN mkdir -p /root/.ssh && mkdir -pv /root/.ssh/sockets
RUN echo -e 'Host *\n\tControlPersist yes\n\tControlMaster auto\n\tControlPath  /root/.ssh/sockets/%r@%h-%p\n\tBatchMode yes\n\tStrictHostKeyChecking no\n\tPort 22' > ~/.ssh/config
ADD . .

CMD ["sh", "-c", "\
    cat webrtc.drs  | dry-stack swarm_deploy --tls-domain=gis-master.ru -x ssh://gis-master.ru -- --prune \n\
"]
