# Отключаем JetStream
jetstream: false

# Включаем WebSocket
websocket: {
  listen: 0.0.0.0:9222
  tls {
    cert_file: "/etc/nats/certs/fullchain.pem"
    key_file:  "/etc/nats/certs/privkey.pem"
  }
  compression: true
}
