server {
    listen 8000 default_server;
    server_name _;

    sendfile on;

    default_type application/octet-stream;

    root /usr/share/nginx/html;

    gzip_static       on;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
